version: "3"
services:
  mariadb:
    image: mariadb:latest
    environment:
      - MARIADB_USER=example-user
      - MARIADB_PASSWORD=my_cool_secret
      - MARIADB_ROOT_PASSWORD=my-secret-pw
      - MARIADB_DATABASE=wordpress
# Uncomment these lines if you need to access mariadb from the host
#    ports:
#      - "3306:3306"
    volumes:
      - ./mariadb_data/:/var/lib/mysql/
  httpd:
    image: httpd:2.4
    ports:
     - "8080:80"
    volumes:
      - ./public-html/:/usr/local/apache2/htdocs/
